version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  rich_console:
    format: '%(message)s'
    datefmt: '[%X]'
    class: rich.logging.RichHandler
    level: INFO
    rich_tracebacks: True
    tracebacks_show_locals: True
  json_file:
    format: '{"timestamp": "%(asctime)s", "name": "%(name)s", "level": "%(levelname)s", "message": "%(message)s", "pathname": "%(pathname)s", "lineno": %(lineno)d}'
    datefmt: '%Y-%m-%dT%H:%M:%S%z'

handlers:
  console:
    class: rich.logging.RichHandler # Using RichHandler for console
    level: INFO
    formatter: rich_console
    show_path: False # Don't show path in rich handler
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json_file # Using JSON formatter for file
    filename: irontorch.log # Default filename, can be overridden
    maxBytes: 10485760 # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  irontorch:
    level: DEBUG
    handlers: [console, file]
    propagate: no # Prevent propagation to root logger

root:
  level: WARNING
  handlers: [console] # Root logger only uses console by default

